CC := nvcc
CFLAGS := -g -O3

all: generate_bodies simulate_n_body simulate_n_body_ver1 .extract-inputs

clean:
	rm -f generate_bodies simulate_n_body simulate_n_body_ver1
	rm -f *.o
	rm -f .extract-inputs

generate_bodies: generate_bodies.cu util.h Makefile
	$(CC) $(CFLAGS) -o generate_bodies generate_bodies.cu

simulate_n_body: simulate_n_body.cu util.h Makefile
	$(CC) $(CFLAGS) -o simulate_n_body simulate_n_body.cu

simulate_n_body_ver1: simulate_n_body_ver1.c util.h Makefile
	$(CC) $(CFLAGS) -o simulate_n_body_ver1 simulate_n_body_ver1.c

.extract-inputs:
	tar xvzf inputs.tar.gz
	touch .extract-inputs

zip:
	@echo "Generating nbody.zip file to submit..."
	@zip -q -r nbody.zip . -x .git/\* .vscode/\* .clang-format .gitignore inputs.tar.gz inputs/\*
	@echo "Done. Please upload nbody.zip to submit."

format:
	@echo "Reformatting source code."
	@clang-format -i --style=file $(wildcard *.c) $(wildcard *.h) $(wildcard *.cu)
	@echo "Done."

.PHONY: all clean zip format